name: weather_mobile
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  adaptive_theme: 2.3.0
  bloc: 8.0.3
  domain:
    path: packages/domain
  equatable: 2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: 1.0.3  
  fpdart: 0.0.14
  get_it: 7.2.0
  google_fonts: 2.3.1
  intl: 0.17.0
  mockingjay: 0.3.0-dev.1
  remote:
    path: packages/remote
  stream_transform: 2.0.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  lint: 1.8.2
  mocktail: 0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/svg/
    - assets/svg/weather/
