name: remote
description: Remote layer
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dio: 4.0.4
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  fpdart: ^0.0.14
  get_it: ^7.2.0
  json_annotation: 4.4.0
  json_serializable: 6.1.4
  retrofit: 3.0.1+1

dev_dependencies:
  build_runner: 2.1.7
  coverage: ^1.1.0
  lint: 1.8.2
  mocktail: ^0.2.0
  retrofit_generator: 4.0.1
  test: ^1.19.2
  very_good_analysis: ^2.4.0
